export const movieGenres = [
  { id: 1, genreName: 'Екшн', checked: false },
  { id: 2, genreName: 'Пригоди', checked: false },
  { id: 3, genreName: 'Комедія', checked: false },
  { id: 4, genreName: 'Драма', checked: false },
  { id: 5, genreName: 'Фантастика', checked: false },
  { id: 6, genreName: 'Жахи', checked: false },
  { id: 7, genreName: 'Трилер', checked: false },
  { id: 8, genreName: 'Фентезі', checked: false },
  { id: 9, genreName: 'Романтика', checked: false },
  { id: 10, genreName: 'Містика', checked: false },
  { id: 11, genreName: 'Вестерн', checked: false },
  { id: 12, genreName: 'Кримінальний', checked: false },
  { id: 13, genreName: 'Документальний', checked: false },
  { id: 14, genreName: 'Нуар', checked: false },
  { id: 15, genreName: 'Мюзикл', checked: false },
  { id: 16, genreName: 'Спортивний', checked: false },
  { id: 17, genreName: 'Військовий', checked: false },
  { id: 18, genreName: 'Сімейний', checked: false },
  { id: 19, genreName: 'Детективний', checked: false },
  { id: 20, genreName: 'Історичний', checked: false },
  { id: 21, genreName: 'На реальних подіях', checked: false },
  { id: 22, genreName: 'Біографічний', checked: false },
  { id: 23, genreName: 'Політичний', checked: false },
  { id: 24, genreName: 'Антиутопія', checked: false },
  { id: 25, genreName: 'Психологічний', checked: false },
  { id: 26, genreName: 'Комікс', checked: false },
];
